<?php
// Generated by the YunoHost installer. Holds *static* paths only —
// runtime-editable settings (Telegram credentials, etc.) live in
// __DATA_DIR__/settings.json and are managed via the web UI.

return [
    'addresses_path'      => '__DATA_DIR__/addresses.json',
    'settings_path'       => '__DATA_DIR__/settings.json',
    'poll_interval_human' => 'every 5 minutes',
];
