#!/bin/bash
# btcwatch remove script.

source /usr/share/yunohost/helpers

ynh_script_progression --message="Removing cron job..."
ynh_safe_rm "/etc/cron.d/$app"

ynh_script_progression --message="Removing PHP-FPM pool..."
ynh_config_remove_phpfpm

ynh_script_progression --message="Removing nginx site..."
ynh_config_remove_nginx

ynh_script_progression --message="Removing logrotate..."
ynh_config_remove_logrotate

ynh_script_progression --message="Removing log dir..."
ynh_safe_rm "/var/log/$app"

# install_dir / data_dir / system_user are torn down automatically by the
# resource manager declared in manifest.toml.

ynh_script_progression --message="Removal completed"
